apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  hosts:
  - "argocd.chuchodavids.io"
  gateways:
  - istio-system/istio-gw
  http:
  - match:
    - uri:
        regex: "argocd.*"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80