apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: "0.1"
              memory: "50Mi"
            limits:
              cpu: "0.2"
              memory: "70Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          resources:
            requests:
              cpu: "0.1"
              memory: "50Mi"
            limits:
              cpu: "0.2"
              memory: "150Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          resources:
            requests:
              cpu: "0.2"
              memory: "60Mi"
            limits:
              cpu: "0.3"
              memory: "100Mi"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              cpu: "0.2"
              memory: "70Mi"
            limits:
              cpu: "0.3"
              memory: "450Mi"