
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sonarr
  namespace: media-server
  labels:
    app:  sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app:  sonarr
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  sonarr
        image: ghcr.io/linuxserver/sonarr
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1024m
            memory: 1Gi
        #livenessProbe:
          #httpGet:
            #path: /settings
            #port: 7878
          #initialDelaySeconds: 30
          #timeoutSeconds: 5
          #successThreshold: 1
          #failureThreshold: 3
          #periodSeconds: 10
        #readinessProbe:
          #httpGet:
            #path: /_status/healthz
            #port: 80
          #initialDelaySeconds: 5
          #timeoutSeconds: 2
          #successThreshold: 1
          #failureThreshold: 3
          #periodSeconds: 10
        env:      
        - name: PUID
          value: "10050"
        - name: PGID
          value: "10050"
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort:  7878
          name:  http
        volumeMounts:
        - name: pv-shows
          mountPath: /data/shows
        - name: nfs-appdata
          mountPath: /config
        - name: pv-downloads
          mountPath: /data/downloads
      volumes:
        - name: pv-downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: pv-shows
          persistentVolumeClaim:
            claimName: pvc-shows
        - name: nfs-appdata
          persistentVolumeClaim:
            claimName: claim-appdata-sonarr
      restartPolicy: Always

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-downloads
  resources:
    requests:
      storage: 10Mi   

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shows
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-shows
  resources:
    requests:
      storage: 10Mi   

---

#appdata

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-appdata-sonarr
  namespace: media-server
  labels:
    app: sonarr
  annotations:
    nfs.io/storage-path: "sonarr"
spec:
  storageClassName: nfs-appdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi


---

#Service


apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media-server
spec:
  selector:
    app: sonarr
  type: LoadBalancer
  ports:
  - name: sonarr
    port: 7878
    targetPort: 7878
    protocol: TCP