
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hydra2
  namespace: media-server
  labels:
    app:  hydra2
spec:
  selector:
    matchLabels:
      app: hydra2
  replicas: 1
  template:
    metadata:
      labels:
        app:  hydra2
    spec:
      containers:
      - name:  hydra2
        securityContext:
          runAsUser: 1001
        image: ghcr.io/linuxserver/nzbhydra2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
        #livenessProbe:
          #httpGet:
            #path: /
            #port: 7878
          #initialDelaySeconds: 30
          #timeoutSeconds: 5
          #successThreshold: 1
          #failureThreshold: 3
          #periodSeconds: 10
        #readinessProbe:
          #httpGet:
            #path: /_status/healthz
            #port: 80
          #initialDelaySeconds: 5
          #timeoutSeconds: 2
          #successThreshold: 1
          #failureThreshold: 3
          #periodSeconds: 10
        env:      
        - name: PUID
          value: "10050"
        - name: PGID
          value: "10050"
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort:  7878
          name:  http
        volumeMounts:
        - name: pv-downloads
          mountPath: /data/downloads
        - name: nfs-appdata
          mountPath: /config
      volumes:
        - name: pv-downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: nfs-appdata
          persistentVolumeClaim:
            claimName: claim-appdata-hydra2
      restartPolicy: Always

---
#downloads

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-downloads
  resources:
    requests:
      storage: 10Mi   


---

#appdata

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-appdata-hydra2
  namespace: media-server
  labels:
    app: hydra2
  annotations:
    nfs.io/storage-path: "hydra2"
spec:
  storageClassName: nfs-appdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi


---

#Service

apiVersion: v1
kind: Service
metadata:
  name: hydra2
  namespace: media-server
spec:
  selector:
    app: hydra2
  type: LoadBalancer
  ports:
  - name: hydra2
    port: 5076
    targetPort: 5076
    protocol: TCP