
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-server
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: ghcr.io/linuxserver/radarr
        imagePullPolicy: IfNotPresent
        #securityContext:
          #runAsUser: 1001
        resources:
          requests:
            cpu: 300m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 7878
          initialDelaySeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
              - cat
              - /data/movies/health
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 4
        env:      
        - name: PUID
          value: "10050"
        - name: PGID
          value: "10050"
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort:  7878
          name:  http
        volumeMounts:
        - name: pv-downloads
          mountPath: /data/downloads
        - name: pv-movies
          mountPath: /data/movies
        - name: gs-appdata
          mountPath: /config
      volumes:
        - name: pv-movies
          persistentVolumeClaim:
            claimName: pvc-movies
        - name: pv-downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: gfs-appdata
          glusterfs:
            endpoints: glustefs-cluster
            path: gv0/appdata/radarr
      restartPolicy: Always

---
#Service


apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media-server
spec:
  selector:
    app: radarr
  type: LoadBalancer
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878
    protocol: TCP