
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-server
  labels:
    app: sabnzbd
spec:
  selector:
    matchLabels:
      app: sabnzbd
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: ghcr.io/linuxserver/sabnzbd
        imagePullPolicy: IfNotPresent
        #securityContext:
          #runAsUser: 1001
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 60
        #readinessProbe:
          #httpGet:
            #path: /_status/healthz
            #port: 80
          #initialDelaySeconds: 5
          #timeoutSeconds: 2
          #successThreshold: 1
          #failureThreshold: 3
          #periodSeconds: 10
        env:      
        - name: PUID
          value: "10050"
        - name: PGID
          value: "10050"
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort:  8080
          name:  http
        volumeMounts:
        - name: pv-downloads
          mountPath: /data/downloads
        - name: nfs-appdata
          mountPath: /config
      volumes:
        - name: pv-downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: nfs-appdata
          persistentVolumeClaim:
            claimName: claim-appdata-sabnzbd
      restartPolicy: Always

---

#downloads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-downloads
  resources:
    requests:
      storage: 10Mi   


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-movies
  resources:
    requests:
      storage: 10Mi   

---

#appdata

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-appdata-sabnzbd
  namespace: media-server
  labels:
    app: sabnzbd
  annotations:
    nfs.io/storage-path: "sabnzbd"
spec:
  storageClassName: nfs-appdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi


---

#Service


apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media-server
spec:
  selector:
    app: sabnzbd
  type: LoadBalancer
  ports:
  - name: sabnzbd
    port: 8080 
    targetPort: 8080
    protocol: TCP