apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: Y2h1Y2hvZGF2aWRz
  AWS_SECRET_ACCESS_KEY: cG9sbG8xLi4=
  AWS_ENDPOINTS: aHR0cDovLzE5Mi4xNjguMjAwLjE2OTo5NzY4
