apiVersion: v1
kind: ServiceAccount
metadata:
  name: media
  namespace: media-server
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: regular
  # replace with namespace where provisioner is deployed
  namespace: media-server
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-media
  # replace with namespace where provisioner is deployed
  namespace: media-server
subjects:
  - kind: ServiceAccount
    name: media
    # replace with namespace where provisioner is deployed
    namespace: media-server
roleRef:
  kind: Role
  name: regular
  apiGroup: rbac.authorization.k8s.io