apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  project: default

  source:
    repoURL: https://github.com/Chuchodavids/m0n3t.git
    targetRevision: HEAD
    path: bookinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
