apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
# BOOKINFO
  - port:
      number: 80
      name: http-bookinfo
      protocol: HTTP
    hosts:
      - "bookinfo/test.chuchodavids.io"
    tls:
      httpsredirect: true
  - port:
      number: 443
      name: https-bookinfo
      protocol: HTTPS
    hosts:
      - "bookinfo/test.chuchodavids.io"
    tls:
      mode: SIMPLE
      credentialName: chuchodavids-io-cert
  - port:
      number: 80
      name: http-argocd
      protocol: HTTP
    hosts:
      - "*"