- hosts: all
  tasks:
  # install dependencies
    - name: Install packages
      apt:
        name:
          - curl
          - apt-transport-https
          - vim
          - git
          - wget
          - gnupg2
          - software-properties-common
          - ca-certificates
          - lsb-release

# add google repo

    - name: add google key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
        state: present

    - name: Add google repo
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

# install kubernetes
    - name: install kubernetes
      apt: 
        name: 
          - kubelet
          - kubeadm
          - kubectl
# hold kube packages

    - name: hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold

    - name: hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold

# Swapp off  

    - name: swapoff
      command: "swapoff -a"
      register: result

# Modprobe stuff

    - name: modprobe
      command: "modprobe overlay"
      register: result

    - name: netfilter
      command: "modprobe br_netfilter"
      register: result
    
    
    - name: netbridge
      copy:
        content: "net.bridge.bridge-nf-call-ip6tables = 1 \nnet.bridge.bridge-nf-call-iptables = 1 \nnet.ipv4.ip_forward = 1"
        dest: /etc/sysctl.d/kubernetes.conf

# Docker config
    - name: add docker key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker
      apt:
        name:
          - containerd.io=1.2.13-2
          - docker-ce=5:19.03.11~3-0~ubuntu-focal
          - docker-ce-cli=5:19.03.11~3-0~ubuntu-focal

    - name: docker system enable
      command: "mkdir -p /etc/systemd/system/docker.service.d"
      register: result

    - name: docker daemon
      ansible.builtin.script: 
        cmd: .docker-daemon.sh
      args:
        creates: /etc/docker/daemon.json 