
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-appdata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  pathPattern: "${.PVC.namespace}/appdata/${.PVC.annotations.nfs.io/storage-path}"  # this will create a folder with the name of the namespace, then a folder "appdata" and finally the name in the annotation for the container
  onDelete: retain
