apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-movies
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169
    path: "/mnt/user/Movies" 
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shows
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169
    path: "/mnt/user/Shows" 


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-downloads
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169
    path: "/mnt/user/Downloads"
