# movies

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-movies
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169  # ip NFS server
    path: "/mnt/user/Movies"  # Path for movies
    
---

# shows

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shows
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169  # ip NFS Server
    path: "/mnt/user/Shows"   # Path for shows


---

# downloads

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-downloads
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169  #ip NFS server 
    path: "/mnt/user/Downloads" # Path for Downloads

---


# documents

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-documents
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.169  # Ip NFS server
    path: "/mnt/user/paperless/smb"  # Path for documents
