#downloads
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-downloads
  namespace: media-server
spec:
  storageClassName: nfs-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi


---
#appdata
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-appdata
  namespace: media-server
spec:
  storageClassName: nfs-appdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi  

---

# Movies
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-movies
  resources:
    requests:
      storage: 10Mi  



---

# Shows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shows
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-shows
  resources:
    requests:
      storage: 10Mi   
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-documents
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: ""
  volumeName: pv-documents
  resources:
    requests:
      storage: 10Mi   
