kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: media-server
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim


---


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: media-server
  annotations:
    foldername: testing
spec:
  storageClassName: nfs-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi